### ISSUE TITLE
Handling of special characters and white space in alias names

### ISSUE THREAD

**Issue by lenkan** [WebOfTrust/signify-ts#204] opened 2024-01-26 08:37 UTC
When creating an identifier with "special" characters, for example spaces or the "ö" letter used in Swedish and Finnish:

```js
    const alias = 'ö';
    const result = await client.identifiers().create(alias, {});
    await waitOperation(client, await result.op());
```

You will get an error when signify-ts is doing the fetch call:

```
    TypeError: fetch failed

      204 |             });
      205 |         }
    > 206 |         const res = await fetch(this.url + path, {
          |                     ^
      207 |             method: method,
      208 |             body: _body,
      209 |             headers: final_headers,

      at async SignifyClient.fetch (../../src/keri/app/clienting.ts:206:21)
      at async EventResult.op (../../src/keri/app/aiding.ts:467:21)
      at async Object.<anonymous> (identifier-name-with-special-chars.test.ts:8:33)

    Cause:
    RequestContentLengthMismatchError: Request body length does not match content-length header
```

I also experimented with URL encoding the alias:

```js
    const alias = encodeURIComponent('ö');
    const result = await client.identifiers().create(alias, {});
    await waitOperation(client, await result.op());

    // Call below fails with a 401 Unauthorized
    const id = await client.identifiers().get(alias);
```

Then the creation succeeds, but a subsequent `identifiers().get(alias)` results in a 401 Unauthorized from keria. The same thing happens when creating an alias with spaces:

```js
    const alias = "a b";
    const result = await client.identifiers().create(alias, {});
    await waitOperation(client, await result.op());

    
    // Call below fails with a 401 Unauthorized
    const id = await client.identifiers().get(alias);
```

I have put the reproduction scripts here: https://github.com/lenkan/signify-ts/blob/2d21adae1f3706f7829566d9af10f0f57d8741dc/examples/integration-scripts/identifier-name-with-special-chars.test.ts

Not sure if this issue should be in signify-ts or in keria. Depending on the route taken, it could affect both repos. I am totally fine with rejecting special characters in identifier names altogether, but then we should probably do some request input validation in keria to reject any invalid requests with a 4xx error.

**Comment by 2byrds** [comment] 2024-04-25 14:51
From our keri dev meeting:
What is the expected behavior for alias names?
Should we be able to support all utf-8?
Localisation is a broader discussion.
The alias is in the path and is encoded.
A fix was added where the content length header was being manually calculated instead of by the fetch.
Probably it was unauthorized because the path changed and the verification of the signature failed.
Its safest thing is to avoid aliases in the urls.
https://github.com/WebOfTrust/keria/issues/202
https://github.com/WebOfTrust/keria/issues/217

**Comment by iFergal** [comment] 2024-10-09 19:47
So that work is done in KERIA now to use the identifier in the URL path. You can still run into issues because the name can still be used in the path (which I think is still useful for testing/prototyping) but maybe it's OK. I'd like to implement https://github.com/WebOfTrust/keria/issues/287#issuecomment-2341186461 in a few months which would avoid this issue anyway.

Maybe we can close this now? We also have that fix for the content length in, I'm able to create identifiers with these names.

**Comment by lenkan** [comment] 2024-10-10 19:19
If we can use the prefix instead of alias in the URLs, I am happy to close this issue. We're still on the old version so haven't tested that feature extensively.

**Closed** 2024-10-17 13:41 UTC
